import { FileHelper, z } from '@start9labs/start-sdk'
import { sdk } from '../sdk'
import { configFileName } from '../utils'

/**
 * The gateway's config file, regenerated by main.ts on every start from the
 * store and the node's RPC cookie. Loosely typed: it is an output, never read
 * back as settings.
 */
export const datumConfigJson = FileHelper.json(
  { base: sdk.volumes.main, subpath: `./${configFileName}` },
  z.record(z.string(), z.any()),
)
